version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: my_portfolio
    path: templates/
    text-resources:
      - path: "*.html"
        format: html-hardcoded
